/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package contabilidad;

import java.awt.Image;
import java.awt.Toolkit;
import java.awt.print.PrinterException;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author user
 */
public class inaterfaz extends javax.swing.JFrame {
      DefaultTableModel tabla = new DefaultTableModel();
      DefaultTableModel caja = new DefaultTableModel();
      DefaultTableModel banco = new DefaultTableModel();
       DefaultTableModel inver = new DefaultTableModel();
       DefaultTableModel clientes = new DefaultTableModel();
      DefaultTableModel documentos = new DefaultTableModel();
       DefaultTableModel deudores = new DefaultTableModel();
         DefaultTableModel ivaacreditar = new DefaultTableModel();
         DefaultTableModel ivaacreditable = new DefaultTableModel();
          DefaultTableModel rentas = new DefaultTableModel();
               DefaultTableModel intereces = new DefaultTableModel();
       DefaultTableModel almacen = new DefaultTableModel();
      
       
    /**
     * Creates new form inaterfaz
     */
    public inaterfaz() {
           super("Score Express");
        initComponents();
        
        String [] cajt ={"Debe","Haber"};
        String [] titul={"Cuenta", "Tipo de cuenta", "Debe", "Haber"};
        tabla.setColumnIdentifiers(titul);
        caja.setColumnIdentifiers(cajt);
        jTable1.setModel(tabla);
        caja1.setModel(caja);
        banco.setColumnIdentifiers(cajt);
        banko.setModel(banco);
        inver.setColumnIdentifiers(cajt);
        inversiones.setModel(inver);
        clientes.setColumnIdentifiers(cajt);
        tablaclientes.setModel(clientes);
        documentos.setColumnIdentifiers(cajt);
        tabladocumentos.setModel(documentos);
        deudores.setColumnIdentifiers(cajt);
        tabladeudores.setModel(deudores);
        ivaacreditar.setColumnIdentifiers(cajt);
        tablaivaacreditar.setModel(ivaacreditar);
        ivaacreditable.setColumnIdentifiers(cajt);
        tablaacreditable.setModel(ivaacreditable);
        rentas.setColumnIdentifiers(cajt);
        tablarentas.setModel(rentas);
        intereces.setColumnIdentifiers(cajt);
        tablaintereces.setModel(intereces);
        almacen.setColumnIdentifiers(cajt);
        tablaalmacen.setModel(almacen);
    }

    @Override

    //</editor-fold>
    public Image getIconImage(){
    
        Image retValue=Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("icono/icono.jpg"));
        
    return retValue;
     }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        jComboBox1 = new javax.swing.JComboBox();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        banko = new javax.swing.JTable();
        bandebe = new javax.swing.JLabel();
        banhaber = new javax.swing.JLabel();
        nuba = new javax.swing.JLabel();
        nubh = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        inversiones = new javax.swing.JTable();
        ind = new javax.swing.JLabel();
        inh = new javax.swing.JLabel();
        nind = new javax.swing.JLabel();
        ninh = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        tablaclientes = new javax.swing.JTable();
        cld = new javax.swing.JLabel();
        clh = new javax.swing.JLabel();
        ncld = new javax.swing.JLabel();
        nclh = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane6 = new javax.swing.JScrollPane();
        tabladocumentos = new javax.swing.JTable();
        dod = new javax.swing.JLabel();
        doh = new javax.swing.JLabel();
        ndod = new javax.swing.JLabel();
        ndoh = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane7 = new javax.swing.JScrollPane();
        tabladeudores = new javax.swing.JTable();
        ded = new javax.swing.JLabel();
        deh = new javax.swing.JLabel();
        nded = new javax.swing.JLabel();
        ndeh = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jScrollPane8 = new javax.swing.JScrollPane();
        tablaivaacreditar = new javax.swing.JTable();
        ivd = new javax.swing.JLabel();
        ivh = new javax.swing.JLabel();
        nivd = new javax.swing.JLabel();
        nivh = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        caja1 = new javax.swing.JTable();
        cade = new javax.swing.JLabel();
        caha = new javax.swing.JLabel();
        ncd = new javax.swing.JLabel();
        nch = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jScrollPane9 = new javax.swing.JScrollPane();
        tablaacreditable = new javax.swing.JTable();
        ivad = new javax.swing.JLabel();
        ivah = new javax.swing.JLabel();
        nivad = new javax.swing.JLabel();
        nivah = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jScrollPane10 = new javax.swing.JScrollPane();
        tablarentas = new javax.swing.JTable();
        red = new javax.swing.JLabel();
        reh = new javax.swing.JLabel();
        nred = new javax.swing.JLabel();
        nreh = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        jScrollPane11 = new javax.swing.JScrollPane();
        tablaintereces = new javax.swing.JTable();
        intd = new javax.swing.JLabel();
        inth = new javax.swing.JLabel();
        nintd = new javax.swing.JLabel();
        ninth = new javax.swing.JLabel();
        jPanel11 = new javax.swing.JPanel();
        jScrollPane12 = new javax.swing.JScrollPane();
        tablaalmacen = new javax.swing.JTable();
        ald = new javax.swing.JLabel();
        alh = new javax.swing.JLabel();
        nald = new javax.swing.JLabel();
        nalh = new javax.swing.JLabel();
        debe1 = new javax.swing.JLabel();
        haber1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();

        jMenu1.setText("jMenu1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImage(getIconImage());

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Cuentas", "1101", "1102", "1103", "1104", "1105", "1006", "1107", "1108", "1109", "1110", "1111" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jLabel2.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Cuenta", "Tipo de cuenta", "Debe", "Haber"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jButton1.setText("Agregar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel3.setText("Cuenta");

        jLabel4.setText("Debe");

        jLabel5.setText("Haber");

        banko.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Title 2"
            }
        ));
        jScrollPane3.setViewportView(banko);

        bandebe.setText("0");
        bandebe.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));

        banhaber.setText("0");
        banhaber.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));

        nuba.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));

        nubh.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(64, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(bandebe, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(nuba, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(nubh, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(banhaber, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(70, 70, 70))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(banhaber, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bandebe, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nuba, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nubh, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(55, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Banco", jPanel2);

        inversiones.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Title 2"
            }
        ));
        jScrollPane4.setViewportView(inversiones);

        ind.setText("0");
        ind.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));

        inh.setText("0");
        inh.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));

        nind.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));

        ninh.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(nind, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(ninh, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(ind, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(inh, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(88, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ind)
                    .addComponent(inh))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nind, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ninh, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(52, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Inversiones Temporales", jPanel3);

        tablaclientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Title 2"
            }
        ));
        jScrollPane5.setViewportView(tablaclientes);

        cld.setText("0");
        cld.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));

        clh.setText("0");
        clh.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));

        ncld.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));

        nclh.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                            .addComponent(ncld, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(nclh, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel4Layout.createSequentialGroup()
                            .addGap(0, 0, Short.MAX_VALUE)
                            .addComponent(clh, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(cld, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(83, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cld)
                    .addComponent(clh, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ncld, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nclh, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(60, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Clientes", jPanel4);

        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tabladocumentos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Title 2"
            }
        ));
        jScrollPane6.setViewportView(tabladocumentos);

        jPanel5.add(jScrollPane6, new org.netbeans.lib.awtextra.AbsoluteConstraints(57, 11, 158, 93));

        dod.setText("0");
        dod.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));
        jPanel5.add(dod, new org.netbeans.lib.awtextra.AbsoluteConstraints(57, 110, 68, -1));

        doh.setText("0");
        doh.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));
        jPanel5.add(doh, new org.netbeans.lib.awtextra.AbsoluteConstraints(147, 110, 68, -1));

        ndod.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));
        jPanel5.add(ndod, new org.netbeans.lib.awtextra.AbsoluteConstraints(57, 134, 68, 18));

        ndoh.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));
        jPanel5.add(ndoh, new org.netbeans.lib.awtextra.AbsoluteConstraints(147, 134, 68, 18));

        jTabbedPane1.addTab("Documentos por Cobrar", jPanel5);

        tabladeudores.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Title 2"
            }
        ));
        jScrollPane7.setViewportView(tabladeudores);

        ded.setText("0");
        ded.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));

        deh.setText("0");
        deh.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));

        nded.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));

        ndeh.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(nded, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(ndeh, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(ded, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(deh, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(76, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ded)
                    .addComponent(deh))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nded, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ndeh, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(54, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Deudores Diversos", jPanel6);

        tablaivaacreditar.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Title 2"
            }
        ));
        jScrollPane8.setViewportView(tablaivaacreditar);

        ivd.setText("0");
        ivd.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));

        ivh.setText("0");
        ivh.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));

        nivd.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));

        nivh.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(nivd, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(nivh, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(ivd, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(ivh, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(70, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ivd)
                    .addComponent(ivh))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nivd, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nivh, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(59, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("IVA por Acreditar", jPanel7);

        caja1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Debe", "Haber"
            }
        ));
        jScrollPane2.setViewportView(caja1);

        cade.setText("0");
        cade.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));

        caha.setText("0");
        caha.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));

        ncd.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));

        nch.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(74, 74, 74)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cade, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(ncd, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(nch, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(caha, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(57, 63, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(caha, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cade, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ncd, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nch, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(50, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Caja", jPanel1);

        tablaacreditable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Title 2"
            }
        ));
        jScrollPane9.setViewportView(tablaacreditable);

        ivad.setText("0");
        ivad.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));

        ivah.setText("0");
        ivah.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));

        nivad.setText("0");
        nivad.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));

        nivah.setText("0");
        nivah.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(nivad, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(nivah, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                        .addComponent(ivad, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(ivah, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(73, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ivad)
                    .addComponent(ivah))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nivad)
                    .addComponent(nivah))
                .addContainerGap(65, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("IVA Acreditable", jPanel8);

        jPanel9.setLayout(null);

        tablarentas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Title 2"
            }
        ));
        jScrollPane10.setViewportView(tablarentas);

        jPanel9.add(jScrollPane10);
        jScrollPane10.setBounds(49, 11, 174, 92);

        red.setText("0");
        red.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));
        jPanel9.add(red);
        red.setBounds(49, 109, 65, 18);

        reh.setText("0");
        reh.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));
        jPanel9.add(reh);
        reh.setBounds(158, 109, 65, 18);

        nred.setText("0");
        nred.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));
        jPanel9.add(nred);
        nred.setBounds(49, 138, 65, 18);

        nreh.setText("0");
        nreh.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));
        jPanel9.add(nreh);
        nreh.setBounds(158, 138, 65, 18);

        jTabbedPane1.addTab("Rentas Pagadas por Anticipado", jPanel9);

        tablaintereces.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Title 2"
            }
        ));
        jScrollPane11.setViewportView(tablaintereces);

        intd.setText("0");
        intd.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));

        inth.setText("0");
        inth.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));

        nintd.setText("0");
        nintd.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));

        ninth.setText("0");
        ninth.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                .addContainerGap(77, Short.MAX_VALUE)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addComponent(nintd, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(ninth, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane11, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addComponent(intd, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(inth, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(60, 60, 60))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane11, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(intd)
                    .addComponent(inth))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nintd)
                    .addComponent(ninth))
                .addContainerGap(65, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Intereces Pagados por Anticipado", jPanel10);

        tablaalmacen.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Title 2"
            }
        ));
        jScrollPane12.setViewportView(tablaalmacen);

        ald.setText("0");
        ald.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));

        alh.setText("0");
        alh.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));

        nald.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));

        nalh.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addComponent(nald, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(nalh, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addComponent(ald, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(alh, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane12, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(88, Short.MAX_VALUE))
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane12, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ald)
                    .addComponent(alh))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nald, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nalh, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(59, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Almacén", jPanel11);

        debe1.setText("0");
        debe1.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));

        haber1.setText("0");
        haber1.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));

        jMenu2.setText("Archivo");

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icono/icono_impresora.jpg"))); // NOI18N
        jMenuItem1.setText("Imprimir");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem1);

        jMenu5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icono/images.jpg"))); // NOI18N
        jMenu5.setText("Idioma");

        jMenuItem4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icono/images (1).jpg"))); // NOI18N
        jMenuItem4.setText("Ingles");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem4);

        jMenuItem5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icono/icono-idioma-es.png"))); // NOI18N
        jMenuItem5.setText("Español");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem5);

        jMenu2.add(jMenu5);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Ayuda");

        jMenuItem2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icono/8447_icono_adobe_pdf.jpg"))); // NOI18N
        jMenuItem2.setText("Manual");
        jMenu3.add(jMenuItem2);

        jMenuBar1.add(jMenu3);

        jMenu4.setText("Acerca de");

        jMenuItem3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icono/images (1)_1.jpg"))); // NOI18N
        jMenuItem3.setText("Creditos");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem3);

        jMenuBar1.add(jMenu4);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap(245, Short.MAX_VALUE)
                                .addComponent(debe1, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(23, 23, 23)
                                .addComponent(haber1, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addContainerGap()
                                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(28, 28, 28)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 86, Short.MAX_VALUE)
                                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGap(27, 27, 27)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jTextField1, javax.swing.GroupLayout.DEFAULT_SIZE, 86, Short.MAX_VALUE)
                                        .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGap(28, 28, 28)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 30, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(haber1, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(debe1, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(55, 55, 55)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        try{
        String cuenta = jLabel2.getText();
         int debe = Integer.parseInt(jTextField1.getText());
         int haber = Integer.parseInt(jTextField2.getText());
         int nudebe = Integer.parseInt(debe1.getText());
         int nuhaber = Integer.parseInt(haber1.getText());
        
         
         
         if(jLabel3.getText()== "Cuenta"){
         
         if(cuenta=="Caja" ){
            String valu []= new String[2];
        valu[0]=jTextField1.getText();
            valu[1]=jTextField2.getText();
            caja.addRow(valu);
            
            int f = Integer.parseInt(cade.getText());
            int g = Integer.parseInt(caha.getText());
            int n= f+debe;
            int ns= g+haber;
            
            cade.setText(""+n);
            caha.setText(""+ns);
            
            if(n>ns){
            
            int d = n-ns;
            ncd.setText(""+d);
            
            }else{
            int h= ns-n;
            nch.setText(""+h);
            }
            
            
        } if(cuenta=="Bancos" ){
            String val []= new String[2];
        val[0]=jTextField1.getText();
             val[1]=jTextField2.getText();
            banco.addRow(val);
             int bad= Integer.parseInt(bandebe.getText());
            int bah=Integer.parseInt(banhaber.getText());
            
            int na= bad+debe;
            int nh= bah+haber;
            
            bandebe.setText(""+na);
            banhaber.setText(""+nh);
            if(na>nh){
               int a = na-nh; 
               nuba.setText(""+a); 
                     }else{
            int i = nh-na;
            nubh.setText(""+i);
            }
            
        }
        //
        if(cuenta=="Inversiones Temporales" ){
            String val []= new String[2];
        val[0]=jTextField1.getText();
             val[1]=jTextField2.getText();
            inver.addRow(val);
            
            int f = Integer.parseInt(ind.getText());
            int g = Integer.parseInt(inh.getText());
            int n= f+debe;
            int ns= g+haber;
            
            ind.setText(""+n);
            inh.setText(""+ns);
            
            if(n>ns){
            
            int d = n-ns;
            nind.setText(""+d);
            
            }else{
            int h= ns-n;
            ninh.setText(""+h);
            }
            
        }
        if(cuenta=="Clientes" ){
            String valu []= new String[2];
        valu[0]=jTextField1.getText();
            valu[1]=jTextField2.getText();
            clientes.addRow(valu);
            
            int f = Integer.parseInt(cld.getText());
            int g = Integer.parseInt(clh.getText());
            int n= f+debe;
            int ns= g+haber;
            
            cld.setText(""+n);
            clh.setText(""+ns);
            
            if(n>ns){
            
            int d = n-ns;
            ncld.setText(""+d);
            
            }else{
            int h= ns-n;
            nclh.setText(""+h);
            }
            
            
        } if(cuenta=="Documentos por Cobrar" ){
            String valu []= new String[2];
        valu[0]=jTextField1.getText();
            valu[1]=jTextField2.getText();
            documentos.addRow(valu);
            
            int f = Integer.parseInt(dod.getText());
            int g = Integer.parseInt(doh.getText());
            int n= f+debe;
            int ns= g+haber;
            
            dod.setText(""+n);
            doh.setText(""+ns);
            
            if(n>ns){
            
            int d = n-ns;
            ndod.setText(""+d);
            
            }else{
            int h= ns-n;
            ndoh.setText(""+h);
            }
            
            
        }if(cuenta=="Deudores Diversos" ){
            String valu []= new String[2];
        valu[0]=jTextField1.getText();
            valu[1]=jTextField2.getText();
            deudores.addRow(valu);
            
            int f = Integer.parseInt(ded.getText());
            int g = Integer.parseInt(deh.getText());
            int n= f+debe;
            int ns= g+haber;
            
            ded.setText(""+n);
            deh.setText(""+ns);
            
            if(n>ns){
            
            int d = n-ns;
            nded.setText(""+d);
            
            }else{
            int h= ns-n;
            ndeh.setText(""+h);
            }
            
            
        }
        if(cuenta=="IVA por Acreditar" ){
            String valu []= new String[2];
        valu[0]=jTextField1.getText();
            valu[1]=jTextField2.getText();
            ivaacreditar.addRow(valu);
            
            int f = Integer.parseInt(ivd.getText());
            int g = Integer.parseInt(ivh.getText());
            int n= f+debe;
            int ns= g+haber;
            
            ivd.setText(""+n);
            ivh.setText(""+ns);
            
            if(n>ns){
            
            int d = n-ns;
            nivd.setText(""+d);
            
            }else{
            int h= ns-n;
            nivh.setText(""+h);
            }
            
            
        }
        
        if(cuenta=="IVA Acreditable" ){
            String valu []= new String[2];
        valu[0]=jTextField1.getText();
            valu[1]=jTextField2.getText();
            ivaacreditable.addRow(valu);
            
            int f = Integer.parseInt(ivad.getText());
            int g = Integer.parseInt(ivah.getText());
            int n= f+debe;
            int ns= g+haber;
            
            ivad.setText(""+n);
            ivah.setText(""+ns);
            
            if(n>ns){
            
            int d = n-ns;
            nivad.setText(""+d);
            
            }else{
            int h= ns-n;
            nivah.setText(""+h);
            }
            
            
        }if(cuenta=="Rentas Pagadas por Anticipado" ){
            String valu []= new String[2];
        valu[0]=jTextField1.getText();
            valu[1]=jTextField2.getText();
            rentas.addRow(valu);
            
            int f = Integer.parseInt(red.getText());
            int g = Integer.parseInt(reh.getText());
            int n= f+debe;
            int ns= g+haber;
            
            red.setText(""+n);
            reh.setText(""+ns);
            
            if(n>ns){
            
            int d = n-ns;
            nred.setText(""+d);
            
            }else{
            int h= ns-n;
            nreh.setText(""+h);
            }
            
            
        }if(cuenta=="Intereces Pagados por Anticipado" ){
            String valu []= new String[2];
        valu[0]=jTextField1.getText();
            valu[1]=jTextField2.getText();
            intereces.addRow(valu);
            
            int f = Integer.parseInt(intd.getText());
            int g = Integer.parseInt(inth.getText());
            int n= f+debe;
            int ns= g+haber;
            
            intd.setText(""+n);
            inth.setText(""+ns);
            
            if(n>ns){
            
            int d = n-ns;
            nintd.setText(""+d);
            
            }else{
            int h= ns-n;
            ninth.setText(""+h);
            }
            
            
        }
        if(cuenta=="Almacén" ){
            String valu []= new String[2];
        valu[0]=jTextField1.getText();
            valu[1]=jTextField2.getText();
            almacen.addRow(valu);
            
            int f = Integer.parseInt(ald.getText());
            int g = Integer.parseInt(alh.getText());
            int n= f+debe;
            int ns= g+haber;
            
            ald.setText(""+n);
            alh.setText(""+ns);
            
            if(n>ns){
            
            int d = n-ns;
            nald.setText(""+d);
            
            }else{
            int h= ns-n;
            nalh.setText(""+h);
            }
            
            
            
        }
        String valores []= new String[4];
        if(jLabel2.getText()== "Almacén"){
        valores[0]="1111";
        }
        if(jLabel2.getText()== "Intereces Pagados por Anticipado"){
        valores[0]="1110";
        }
        if(jLabel2.getText()== "Rentas Pagadas por Anticipado"){
        valores[0]="1109";
        }
        if(jLabel2.getText()== "IVA Acreditable"){
        valores[0]="1108";
        }
        if(jLabel2.getText()== "IVA por Acreditar"){
        valores[0]="1107";
        }
         if(jLabel2.getText()== "Deudores Diversos"){
        valores[0]="1106";
        }
          if(jLabel2.getText()== "Documentos por Cobrar"){
        valores[0]="1105";
        }
           if(jLabel2.getText()== "Clientes"){
        valores[0]="1104";
        }
            if(jLabel2.getText()== "Inversiones Temporales"){
        valores[0]="1103";
        }
              if(jLabel2.getText()== "Bancos"){
        valores[0]="1102";
        }
                if(jLabel2.getText()== "Caja"){
        valores[0]="1101";
        }
        valores [1]= jLabel2.getText();
        jLabel2.setText(null);
        valores [2]= jTextField1.getText();
        jTextField1.setText(null);
        valores [3]= jTextField2.getText();
        jTextField2.setText(null);
        tabla.addRow(valores);
        
       int de= nudebe + debe;
       int ha= nuhaber + haber;
       
       debe1.setText(""+de);
       haber1.setText(""+ha);
         
         }
       // de Espeñol a ingles
       if(jLabel3.getText()== "Account"){
         
         if(cuenta=="Cash Account" ){
            String valu []= new String[2];
        valu[0]=jTextField1.getText();
            valu[1]=jTextField2.getText();
            caja.addRow(valu);
            
            int f = Integer.parseInt(cade.getText());
            int g = Integer.parseInt(caha.getText());
            int n= f+debe;
            int ns= g+haber;
            
            cade.setText(""+n);
            caha.setText(""+ns);
            
            if(n>ns){
            
            int d = n-ns;
            ncd.setText(""+d);
            
            }else{
            int h= ns-n;
            nch.setText(""+h);
            }
            
            
        } if(cuenta=="Bank" ){
            String val []= new String[2];
        val[0]=jTextField1.getText();
             val[1]=jTextField2.getText();
            banco.addRow(val);
             int bad= Integer.parseInt(bandebe.getText());
            int bah=Integer.parseInt(banhaber.getText());
            
            int na= bad+debe;
            int nh= bah+haber;
            
            bandebe.setText(""+na);
            banhaber.setText(""+nh);
            if(na>nh){
               int a = na-nh; 
               nuba.setText(""+a); 
                     }else{
            int i = nh-na;
            nubh.setText(""+i);
            }
            
        }
        //
        if(cuenta=="Temporary Investments" ){
            String val []= new String[2];
        val[0]=jTextField1.getText();
             val[1]=jTextField2.getText();
            inver.addRow(val);
            
            int f = Integer.parseInt(ind.getText());
            int g = Integer.parseInt(inh.getText());
            int n= f+debe;
            int ns= g+haber;
            
            ind.setText(""+n);
            inh.setText(""+ns);
            
            if(n>ns){
            
            int d = n-ns;
            nind.setText(""+d);
            
            }else{
            int h= ns-n;
            ninh.setText(""+h);
            }
            
        }
        if(cuenta=="Customers" ){
            String valu []= new String[2];
        valu[0]=jTextField1.getText();
            valu[1]=jTextField2.getText();
            clientes.addRow(valu);
            
            int f = Integer.parseInt(cld.getText());
            int g = Integer.parseInt(clh.getText());
            int n= f+debe;
            int ns= g+haber;
            
            cld.setText(""+n);
            clh.setText(""+ns);
            
            if(n>ns){
            
            int d = n-ns;
            ncld.setText(""+d);
            
            }else{
            int h= ns-n;
            nclh.setText(""+h);
            }
            
            
        } if(cuenta=="Note Receivables" ){
            String valu []= new String[2];
        valu[0]=jTextField1.getText();
            valu[1]=jTextField2.getText();
            documentos.addRow(valu);
            
            int f = Integer.parseInt(dod.getText());
            int g = Integer.parseInt(doh.getText());
            int n= f+debe;
            int ns= g+haber;
            
            dod.setText(""+n);
            doh.setText(""+ns);
            
            if(n>ns){
            
            int d = n-ns;
            ndod.setText(""+d);
            
            }else{
            int h= ns-n;
            ndoh.setText(""+h);
            }
            
            
        }if(cuenta=="Dundry Debtors" ){
            String valu []= new String[2];
        valu[0]=jTextField1.getText();
            valu[1]=jTextField2.getText();
            deudores.addRow(valu);
            
            int f = Integer.parseInt(ded.getText());
            int g = Integer.parseInt(deh.getText());
            int n= f+debe;
            int ns= g+haber;
            
            ded.setText(""+n);
            deh.setText(""+ns);
            
            if(n>ns){
            
            int d = n-ns;
            nded.setText(""+d);
            
            }else{
            int h= ns-n;
            ndeh.setText(""+h);
            }
            
            
        }
        if(cuenta=="VAT Credit" ){
            String valu []= new String[2];
        valu[0]=jTextField1.getText();
            valu[1]=jTextField2.getText();
            ivaacreditar.addRow(valu);
            
            int f = Integer.parseInt(ivd.getText());
            int g = Integer.parseInt(ivh.getText());
            int n= f+debe;
            int ns= g+haber;
            
            ivd.setText(""+n);
            ivh.setText(""+ns);
            
            if(n>ns){
            
            int d = n-ns;
            nivd.setText(""+d);
            
            }else{
            int h= ns-n;
            nivh.setText(""+h);
            }
            
            
        }
        
        if(cuenta=="Creditable VAT" ){
            String valu []= new String[2];
        valu[0]=jTextField1.getText();
            valu[1]=jTextField2.getText();
            ivaacreditable.addRow(valu);
            
            int f = Integer.parseInt(ivad.getText());
            int g = Integer.parseInt(ivah.getText());
            int n= f+debe;
            int ns= g+haber;
            
            ivad.setText(""+n);
            ivah.setText(""+ns);
            
            if(n>ns){
            
            int d = n-ns;
            nivad.setText(""+d);
            
            }else{
            int h= ns-n;
            nivah.setText(""+h);
            }
            
            
        }if(cuenta=="Revenue Received In Advance" ){
            String valu []= new String[2];
        valu[0]=jTextField1.getText();
            valu[1]=jTextField2.getText();
            rentas.addRow(valu);
            
            int f = Integer.parseInt(red.getText());
            int g = Integer.parseInt(reh.getText());
            int n= f+debe;
            int ns= g+haber;
            
            red.setText(""+n);
            reh.setText(""+ns);
            
            if(n>ns){
            
            int d = n-ns;
            nred.setText(""+d);
            
            }else{
            int h= ns-n;
            nreh.setText(""+h);
            }
            
            
        }if(cuenta=="Prepaid Interest" ){
            String valu []= new String[2];
        valu[0]=jTextField1.getText();
            valu[1]=jTextField2.getText();
            intereces.addRow(valu);
            
            int f = Integer.parseInt(intd.getText());
            int g = Integer.parseInt(inth.getText());
            int n= f+debe;
            int ns= g+haber;
            
            intd.setText(""+n);
            inth.setText(""+ns);
            
            if(n>ns){
            
            int d = n-ns;
            nintd.setText(""+d);
            
            }else{
            int h= ns-n;
            ninth.setText(""+h);
            }
            
            
        }
        if(cuenta=="Storage" ){
            String valu []= new String[2];
        valu[0]=jTextField1.getText();
            valu[1]=jTextField2.getText();
            almacen.addRow(valu);
            
            int f = Integer.parseInt(ald.getText());
            int g = Integer.parseInt(alh.getText());
            int n= f+debe;
            int ns= g+haber;
            
            ald.setText(""+n);
            alh.setText(""+ns);
            
            if(n>ns){
            
            int d = n-ns;
            nald.setText(""+d);
            
            }else{
            int h= ns-n;
            nalh.setText(""+h);
            }
            
            
        }
        String valores []= new String[4];
        if(jLabel2.getText()== "Storage"){
        valores[0]="1111";
        }
        if(jLabel2.getText()== "Prepaid Interest"){
        valores[0]="1110";
        }
        if(jLabel2.getText()== "Revenue Received In Advance"){
        valores[0]="1109";
        }
        if(jLabel2.getText()== "Creditable VAT"){
        valores[0]="1108";
        }
        if(jLabel2.getText()== "VAT Credit"){
        valores[0]="1107";
        }
         if(jLabel2.getText()== "Dundry Debtors"){
        valores[0]="1106";
        }
          if(jLabel2.getText()== "Note Receivables"){
        valores[0]="1105";
        }
           if(jLabel2.getText()== "Customers"){
        valores[0]="1104";
        }
            if(jLabel2.getText()== "Temporary Investments"){
        valores[0]="1103";
        }
              if(jLabel2.getText()== "Bank"){
        valores[0]="1102";
        }
                if(jLabel2.getText()== "Cash Account"){
        valores[0]="1101";
        }
        valores [1]= jLabel2.getText();
        jLabel2.setText(null);
        valores [2]= jTextField1.getText();
        jTextField1.setText(null);
        valores [3]= jTextField2.getText();
        jTextField2.setText(null);
        tabla.addRow(valores);
        
       int de= nudebe + debe;
       int ha= nuhaber + haber;
       
       debe1.setText(""+de);
       haber1.setText(""+ha);
         }
       
       
       
        }catch(NumberFormatException e){
            if(jLabel3.getText()=="Cuenta"){
        JOptionPane.showMessageDialog(null, "Introduzca un carácter numérico en los campos: \n-Debe\n-Haber", "Error",JOptionPane.ERROR_MESSAGE);
            }
             if(jLabel3.getText()=="Account"){
        JOptionPane.showMessageDialog(null, "Enter a numeric character in the fields \n-Debit amount\n-Asset", "Error",JOptionPane.ERROR_MESSAGE);
            }
            
        }
    
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
        int posicion = jComboBox1.getSelectedIndex();
      if(jLabel3.getText()== "Cuenta"){
        if(posicion==1){
         jLabel2.setText("Caja");
        }
         if(posicion==2){
         jLabel2.setText("Bancos");
        }
          if(posicion==3){
         jLabel2.setText("Inversiones Temporales");
        }
           if(posicion==4){
         jLabel2.setText("Clientes");
        }
            if(posicion==5){
         jLabel2.setText("Documentos por Cobrar");
        }
             if(posicion==6){
         jLabel2.setText("Deudores Diversos");
        }
              if(posicion==7){
         jLabel2.setText("IVA por Acreditar");
        }
               if(posicion==8){
         jLabel2.setText("IVA Acreditable");
        }
                if(posicion==9){
         jLabel2.setText("Rentas Pagadas por Anticipado");
        }
                 if(posicion==10){
         jLabel2.setText("Intereces Pagados por Anticipado");
        }
                  if(posicion==11){
      
         jLabel2.setText("Almacén");
        }
      }
      // ingles
      if(jLabel3.getText()== "Account"){
        if(posicion==1){
         jLabel2.setText("Cash Account");
        }
         if(posicion==2){
         jLabel2.setText("Bank");
        }
          if(posicion==3){
         jLabel2.setText("Temporary Investments");
        }
           if(posicion==4){
         jLabel2.setText("Customers");
        }
            if(posicion==5){
         jLabel2.setText("Note Receivables");
        }
             if(posicion==6){
         jLabel2.setText("Dundry Debtors");
        }
              if(posicion==7){
         jLabel2.setText("VAT Credit");
        }
               if(posicion==8){
         jLabel2.setText("Creditable VAT");
        }
                if(posicion==9){
         jLabel2.setText("Revenue Received In Advance");
        }
                 if(posicion==10){
         jLabel2.setText("Prepaid Interest");
        }
                  if(posicion==11){
      
         jLabel2.setText("Storage");
        }
      }
      
      
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
        credito c = new credito();
        c.setVisible(true);
        c.setSize(486, 242);
        c.setLocationRelativeTo(null);
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        // TODO add your handling code here:
        jMenu2.setText("File");
        jMenu3.setText("Help");
        jButton1.setText("Add");
        jMenuItem1.setText("Print");
        jMenu5.setText("Language");
        jMenuItem4.setText("English");
        jMenuItem5.setText("Spanish");
        jMenuItem2.setText("Guide");
        jMenuItem3.setText("Credits");
        jLabel3.setText("Account");
        jLabel4.setText("Debit amount");
        jLabel5.setText("Assets");
        
        String [] cajt ={"Debit amount","Asset"};
        String [] titul={"Account", "Account type", "Debit amount", "Asset"};
        tabla.setColumnIdentifiers(titul);
        caja.setColumnIdentifiers(cajt);
        jTable1.setModel(tabla);
        caja1.setModel(caja);
        banco.setColumnIdentifiers(cajt);
        banko.setModel(banco);
        inver.setColumnIdentifiers(cajt);
        inversiones.setModel(inver);
        clientes.setColumnIdentifiers(cajt);
        tablaclientes.setModel(clientes);
        documentos.setColumnIdentifiers(cajt);
        tabladocumentos.setModel(documentos);
        deudores.setColumnIdentifiers(cajt);
        tabladeudores.setModel(deudores);
        ivaacreditar.setColumnIdentifiers(cajt);
        tablaivaacreditar.setModel(ivaacreditar);
        ivaacreditable.setColumnIdentifiers(cajt);
        tablaacreditable.setModel(ivaacreditable);
        rentas.setColumnIdentifiers(cajt);
        tablarentas.setModel(rentas);
        intereces.setColumnIdentifiers(cajt);
        tablaintereces.setModel(intereces);
        almacen.setColumnIdentifiers(cajt);
        tablaalmacen.setModel(almacen);
        
  DefaultComboBoxModel combo = new DefaultComboBoxModel();
  jComboBox1.setModel(combo);
  combo.addElement("Account");
  combo.addElement("Cash Account");
  combo.addElement("Bank");
  combo.addElement("Temporary Investments");
  combo.addElement("Customers");
  combo.addElement("Note Receivables");
  combo.addElement("Dundry Debtors");
  combo.addElement("VAT Credit");
  combo.addElement("Creditable VAT");
  combo.addElement("Revenue Received In Advance");
  combo.addElement("Prepaid Interest");
  combo.addElement("Storage");
  
  jTabbedPane1.setTitleAt(0, "Bank"); 
  jTabbedPane1.setTitleAt(1, "Temporary Investments");
  jTabbedPane1.setTitleAt(2, "Customers");  
   jTabbedPane1.setTitleAt(3, "Note Receivables");
   jTabbedPane1.setTitleAt(4, "Dundry Debtors");
   jTabbedPane1.setTitleAt(5, "VAT Credit");
   jTabbedPane1.setTitleAt(6, "Cash Account");
   jTabbedPane1.setTitleAt(7, "Creditable VAT");
   jTabbedPane1.setTitleAt(8, "Revenue Received In Advance");
   jTabbedPane1.setTitleAt(9, "Prepaid Interest");
   jTabbedPane1.setTitleAt(10, "Storage");
  
  
        
       
        
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        // TODO add your handling code here:
        jMenu2.setText("Archivo");
        jMenu3.setText("Ayuda");
        jButton1.setText("Agregar");
        jMenuItem1.setText("Imprimir");
        jMenu5.setText("Idioma");
        jMenuItem4.setText("Ingles");
        jMenuItem5.setText("Español");
        jMenuItem2.setText("Manual");
       
        jMenuItem3.setText("Creditos");
        jLabel3.setText("Cuenta");
        jLabel4.setText("Debe");
        jLabel5.setText("Haber");
        
    String [] cajt ={"Debe","Haber"};
        String [] titul={"Cuenta", "Tipo de cuenta", "Debe", "Haber"};
        tabla.setColumnIdentifiers(titul);
        caja.setColumnIdentifiers(cajt);
        jTable1.setModel(tabla);
        caja1.setModel(caja);
        banco.setColumnIdentifiers(cajt);
        banko.setModel(banco);
        inver.setColumnIdentifiers(cajt);
        inversiones.setModel(inver);
        clientes.setColumnIdentifiers(cajt);
        tablaclientes.setModel(clientes);
        documentos.setColumnIdentifiers(cajt);
        tabladocumentos.setModel(documentos);
        deudores.setColumnIdentifiers(cajt);
        tabladeudores.setModel(deudores);
        ivaacreditar.setColumnIdentifiers(cajt);
        tablaivaacreditar.setModel(ivaacreditar);
        ivaacreditable.setColumnIdentifiers(cajt);
        tablaacreditable.setModel(ivaacreditable);
        rentas.setColumnIdentifiers(cajt);
        tablarentas.setModel(rentas);
        intereces.setColumnIdentifiers(cajt);
        tablaintereces.setModel(intereces);
        almacen.setColumnIdentifiers(cajt);
        tablaalmacen.setModel(almacen);    
        
        DefaultComboBoxModel combo = new DefaultComboBoxModel();
  jComboBox1.setModel(combo);
  combo.addElement("Cuentas");
  combo.addElement("Caja");
  combo.addElement("Banco");
  combo.addElement("Inversiones Temporale");
  combo.addElement("Clientes");
  combo.addElement("Documentos Por Pagar");
  combo.addElement("Deudores Diversos");
  combo.addElement("IVA Por Acreditar");
  combo.addElement("IVA Acreditable");
  combo.addElement("Rentas Pagadas por Anticipado");
  combo.addElement("Intereces Pagados por Anticipado");
  combo.addElement("Almacén");
        
  jTabbedPane1.setTitleAt(0, "Banco"); 
  jTabbedPane1.setTitleAt(1, "Inverciones Temporales");
  jTabbedPane1.setTitleAt(2, "Clientes");  
   jTabbedPane1.setTitleAt(3, "Documentos por cobrar");
   jTabbedPane1.setTitleAt(4, "Deudores Diversos");
   jTabbedPane1.setTitleAt(5, "IVA Por Acreditar");
   jTabbedPane1.setTitleAt(6, "Caja");
   jTabbedPane1.setTitleAt(7, "IVA acreditable");
   jTabbedPane1.setTitleAt(8, "Rentas Pagadas Por Anticipado");
   jTabbedPane1.setTitleAt(9, "Intereses Pagados Por Anticipado");
   jTabbedPane1.setTitleAt(10, "Almacen");
  
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        try{
            jTable1.print();
            tablarentas.print();
        }catch(PrinterException e){
        
        }
           
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(inaterfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(inaterfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(inaterfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(inaterfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new inaterfaz().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ald;
    private javax.swing.JLabel alh;
    private javax.swing.JLabel bandebe;
    private javax.swing.JLabel banhaber;
    private javax.swing.JTable banko;
    private javax.swing.JLabel cade;
    private javax.swing.JLabel caha;
    private javax.swing.JTable caja1;
    private javax.swing.JLabel cld;
    private javax.swing.JLabel clh;
    private javax.swing.JLabel debe1;
    private javax.swing.JLabel ded;
    private javax.swing.JLabel deh;
    private javax.swing.JLabel dod;
    private javax.swing.JLabel doh;
    private javax.swing.JLabel haber1;
    private javax.swing.JLabel ind;
    private javax.swing.JLabel inh;
    private javax.swing.JLabel intd;
    private javax.swing.JLabel inth;
    private javax.swing.JTable inversiones;
    private javax.swing.JLabel ivad;
    private javax.swing.JLabel ivah;
    private javax.swing.JLabel ivd;
    private javax.swing.JLabel ivh;
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane10;
    private javax.swing.JScrollPane jScrollPane11;
    private javax.swing.JScrollPane jScrollPane12;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JLabel nald;
    private javax.swing.JLabel nalh;
    private javax.swing.JLabel ncd;
    private javax.swing.JLabel nch;
    private javax.swing.JLabel ncld;
    private javax.swing.JLabel nclh;
    private javax.swing.JLabel nded;
    private javax.swing.JLabel ndeh;
    private javax.swing.JLabel ndod;
    private javax.swing.JLabel ndoh;
    private javax.swing.JLabel nind;
    private javax.swing.JLabel ninh;
    private javax.swing.JLabel nintd;
    private javax.swing.JLabel ninth;
    private javax.swing.JLabel nivad;
    private javax.swing.JLabel nivah;
    private javax.swing.JLabel nivd;
    private javax.swing.JLabel nivh;
    private javax.swing.JLabel nred;
    private javax.swing.JLabel nreh;
    private javax.swing.JLabel nuba;
    private javax.swing.JLabel nubh;
    private javax.swing.JLabel red;
    private javax.swing.JLabel reh;
    private javax.swing.JTable tablaacreditable;
    private javax.swing.JTable tablaalmacen;
    private javax.swing.JTable tablaclientes;
    private javax.swing.JTable tabladeudores;
    private javax.swing.JTable tabladocumentos;
    private javax.swing.JTable tablaintereces;
    private javax.swing.JTable tablaivaacreditar;
    private javax.swing.JTable tablarentas;
    // End of variables declaration//GEN-END:variables
}
